### ISSUE TITLE
Provide a way to change a repository protocol

### ISSUE THREAD

**Issue by wildart** [JuliaLang/PkgDev.jl#10]
At this point, many packages were generated using `git(+ssh)` protocol in their repositories. This will become a problem as `publish` is going to fail with "unsupported protocol" (related to `libgit2` build).

Possible solutions:
- provide a tool that would change a `push` remote url for repository to use `https` protocol
- try push a repository with remote url converted to `https` protocol (if possible without changing configuration of the repository).

**Comment by tkelman** [comment]
Is this a function of how the package was generated, or how the package was cloned? If the package was cloned with new enough 0.5, shouldn't it have https remotes that PkgDev can push to?

**Comment by wildart** [comment]
Mostly cloned, and a package can be cloned using any `git` client. Plus, `https` has more cumbersome authentication procedure (e.g. 2FA), comparing to `git(+ssh)` protocol, which can be very annoying during the development.

**Comment by tkelman** [comment]
I disagree. I never use ssh, ever, and our libgit2 build doesn't support it either. ssh is not very portable, and doesn't help at all when you work from many different machines on many different OS'es. We shouldn't go too far out of our way to support packages that were cloned by anything other than through `Pkg`.

**Comment by wildart** [comment]
no `ssh`!? :scream: windows user? But, seriously, people expect to use git in day-to-day development not only for publishing, and I'm quite sure that majority of *nix devs primarily use ssh for git. I have many packages that cloned through `https`, but as soon as I start doing `pull` and `push`, everything goes through ssh. Why? Authentication. For `https`, it is clunky, especially in command line and if you add 2FA then entering three times credentials - no way. Devs are going to switch to manual commits to METADATA if we going to constrain tools to `https` protocol only.

I think there is a chance to modify protocol on-fly and do not touch repo configuration with anonymous remotes.

**Comment by tkelman** [comment]
ssh is clunky as hell too - I have to start an agent and authenticate the key, and copy that key to every machine I want to use, and start every instance of julia from within a terminal where an agent has been started? Would rather just type my github password on every push, it's a good sanity check anyway to confirm when you're pushing things. Credential helpers as Keno mentioned elsewhere can make https a little smoother, and it's one fewer library we need to support. If you want to go through ssh remotes, do so on your own on the command line, but supporting them in Pkg is unnecessary extra work. Clone packages via https in Pkg, with default https push remotes for PkgDev to use.

**Comment by timholy** [comment]
Bump. At this point I always just pretend `PkgDev` doesn't exist.

**Comment by tkelman** [comment]
There's a setprotocol in base now.

**Comment by wildart** [comment]
Not relevant anymore. Probably need to remove `setprotocol` from base as well.

**Comment by tkelman** [comment]
https-vs-ssh issues are common enough that setprotocol should stay where it is, it could maybe use better documentation though

**Comment by wildart** [comment]
@tkelman I fill like we swapped our stand on usage on `ssh` (see above comments). Now, after all shenanigans with `ssh` support, I have strong filling that this was a bad idea, and we had to push hard to discourage its use. Well, I believe in a second chance when new release will come.

**Comment by tkelman** [comment]
We didn't fix the usability problems inherent in how ssh itself works. I still don't use it for the same reasons I didn't use it 10 months ago, none of those have changed except that we now build it for people who really want to use it.

**Comment by tkelman** [comment]
ssh should only be used for private packages (and even then, only for git hosts that don't allow oauth token remotes), and we should default to https (using a token fixes the 2FA issue) for public ones.
