### ISSUE TITLE
Segfault/timeout on AppVeyor with Julia nightly

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/PkgDev.jl#103]
AppVeyor has been exhibiting some unfortunate behavior for this repo on Julia 0.6. On 32-bit Windows, it chokes on `jl_write_coverage_data` and spews errors for an hour until the build times out. On 64-bit, it segfaults while trying to run the `PackageWithCodeCoverage` tests.

Most recent master builds:
* 32-bit: https://ci.appveyor.com/project/wildart/pkgdev-jl/branch/master/job/cpok8gntvk7hnhc7
* 64-bit: https://ci.appveyor.com/project/wildart/pkgdev-jl/branch/master/job/w40jvq3m15x6wss9

If this is an upstream issue, feel free to close and I can open this issue elsewhere if needed.

**Comment by tkelman** [comment]
duplicate of https://github.com/JuliaLang/julia/issues/21289 I believe

**Comment by ararslan** [comment]
Ah, okay. Will close in favor of that then.
