### ISSUE TITLE
Failure to PkgDev.publish()

### ISSUE THREAD

**Issue by richardreeve** [JuliaLang/PkgDev.jl#106]
I'm sure I'm doing something very stupid, but I can't work it out. I can't publish a new tag to `METADATA` - the `PkgDev.tag()` itself worked fine, but I get some fatal error every time I try to publish it:

```
julia> PkgDev.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    BioEnergeticFoodWebs v0.3.0 – no valid versions exist for package DiffEqProblemLibrary
    BioEnergeticFoodWebs v0.3.1 – no valid versions exist for package DiffEqProblemLibrary
```

This happens even though I deleted the `.julia/v0.5` folder and reinstalled all of the packages (with or without `BioEnergeticFoodWebs` added)... any suggestions? I know it's **much** more likely to be something to do with me, but is it a problem with `PkgDev` or `METADATA`?

**Comment by tkelman** [comment]
I'm going to close this copy, since it's a resolver / metadata interaction issue that wouldn't be fixed here.
