### ISSUE TITLE
Pkg.generate(pkg, license) has been moved to the package PkgDev.jl.

### ISSUE THREAD

**Issue by ptoche** [JuliaLang/PkgDev.jl#117]
Something wrong? (with my brain?)

    Pkg.add("PkgDev") 
    ## INFO: Nothing to be done
    
    using PkgDev
    Pkg.generate("Blabla", "MIT")
    ## Pkg.generate(pkg, license) has been moved to the package PkgDev.jl.
    ## Run Pkg.add("PkgDev") to install PkgDev on Julia v0.5-

[Reference](https://docs.julialang.org/en/release-0.4/manual/packages/#creating-a-new-package)

**Comment by KristofferC** [comment]
Yes. Write `PkgDev` instead of `Pkg`.

**Comment by ptoche** [comment]
I knew I was being stupid, thanks Kristoffer!
