### ISSUE TITLE
runtests.jl and testset

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/PkgDev.jl#119]
Hello,

it's generally a good idea to run unit tests with `testset` macro
maybe default `runtests.jl` should use `testset`.

Pinging @ararslan 
https://github.com/JuliaLang/PkgDev.jl/issues/118#issuecomment-313936764

Kind regards

**Comment by scls19fr** [comment]
Not sure, if what I was writting previously is clear enough.
A template for `runtests.jl` using `testset` macro could be a good idea

So instead of `runtests.jl` with the following content

```julia
using YourPackage
using Base.Test

# write your own tests here
@test 1 == 2
```

we could have

```
using YourPackage
using Base.Test

@testset "YourPackage" begin
    # write your own tests here
    @test 1 == 2
end
```

**Comment by fredrikekre** [comment]
This is already in PkgTemplates: https://github.com/invenia/PkgTemplates.jl/blob/1e193518229fc4e2a27a451ec1b83d27b5a3989c/src/generate.jl#L207-L215 which might be incorporated into the new package manager https://github.com/StefanKarpinski/Pkg3.jl/issues/23
