### ISSUE TITLE
PkgDev.generate should not enable OS X testing on Travis by default

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/PkgDev.jl#124]
Travis has limited servers for OS X. Most of them [run continuously](https://www.traviscistatus.com/), with a large backlog for open source projects. This results in [long wait times](https://github.com/travis-ci/travis-ci/issues/7304).

Of course code that has OS-specific features should be tested on all possible architectures. But arguably, this is not the case for the typical Julia package. We are contributing to the congestion of a scarce resource that is provided for free. Using it only when necessary would be better.

A single `#` in [the relevant line](https://github.com/JuliaLang/PkgDev.jl/blob/master/src/generate.jl#L234) would be sufficient. Package authors who need OS X testing could just remove it.

**Comment by ararslan** [comment]
I disagree, I think the default should be to test on as many platforms as possible, with library authors disabling irrelevant ones on a case-by-case basis. The Travis queues have definitely been a train wreck lately, but it's possible that Travis will beef up their macOS infrastructure at some point, in which case this would be a non-issue.

**Comment by tpapp** [comment]
In principle I agree (the more testing, the better), but it [doesn't look like](https://blog.travis-ci.com/2017-09-22-macos-update) the issue will be resolved in the near future with the Travis infrastructure.
