### ISSUE TITLE
Generated .gitignore differs from GitHub default

### ISSUE THREAD

**Issue by phipsgabler** [JuliaLang/PkgDev.jl#128]
The default Julia [.gitignore](https://github.com/github/gitignore/blob/b3ae3810f8b0f97f24cd61c2d3dd1b5089b91801/Julia.gitignore), which GitHub can add for you when creating a new repo, contains an additional line, namely `deps/deps.jl`. This line isn't contained in the .gitignore from `generate`, and lead to a merge conflict for me.

Now, I actually don't know whether this line makes it better or worse, but both variants should be consistent, IMO, given how tightly integrated Julia packages are with GitHub. If you argue that this line should not be included, I'll try to get it removed from the defaults repo.

**Comment by ararslan** [comment]
I think `deps/deps.jl` _should_ be included in the default .gitignore, and I agree that they should be consistent.

**Comment by phipsgabler** [comment]
OK, then -- I created a PR.
