### ISSUE TITLE
PkgTemplate should be mentioned in language documentation as PkgDev as there is no plans to bridge the gaps.

### ISSUE THREAD

**Issue by sambitdash** [JuliaLang/PkgDev.jl#137]
A developer may like to have a proprietary license and finally not check-in the code to `GitHub` but point to his own `git` repository. In such a case, the developer also may need an optional `remote origin` metadata point to his own personal `git` repository. 

All these are manually editable but API should have the necessary capabilities. The A.PI is: `PkgDev.generate`

**Comment by sambitdash** [comment]
I was made to realize this is only possible with the package `PkgTemplates`. In that case, the same package should be mentioned in the product documentation as `PkgDev`. The limitations of `PkgDev` are artificial and there is clear mandate not to enhance it to support the customizations you can do with `PkgTemplate`. Under such circumstances, the language documentation should refer to `PkgTemplates` at all places there is reference to `PkgDev`. PR #138 discusses the thread clarifying the `PkgDev` position on the same. 

@StefanKarpinski, please review this.

**Comment by ViralBShah** [comment]
I thought Pkg3 will allow folks to have their own private package repositories, which should address the issue of having proprietary software available through the package ecosystem.

**Comment by StefanKarpinski** [comment]
Private repositories will likely want to have a default proprietary license file instead of making all their developers edit a license file every time, e.g. "Copyright(c) SomeCorp 2018. All Rights Reserved."

**Comment by sambitdash** [comment]
@StefanKarpinski exactly the reason why the license should be made optional in `PkgDev` or any future incarnation of the same.

**Comment by StefanKarpinski** [comment]
We should not be encouraging people to edit license files. Adding a "no license" option to PkgDev which generates an "All Rights Reserved" license file would be fine. The PkgDev infrastructure is also effectively end-of-life and will be replaced as we add comparable functionality to Pkg3.

**Comment by sambitdash** [comment]
Since, `Pkg3` will take up this enhancement, there is no need/urgency for this in this now in the interest of one effort.
