### ISSUE TITLE
RFC: Partial rewrite for 1.0

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/PkgDev.jl#152]
I really liked this workflow on 0.6 and I'd like to get it working with the same API on 1.0. Would anyone be opposed to a partial rewrite to get things working with Pkg3? Maybe Invenia could incorporate PkgTemplates.jl for the generate behaviour?

**Comment by davidanthoff** [comment]
I would _love_ that! I think the API could be slightly tweaked? I think we probably wouldn't need `register`, `publish`, `license` (not sure about that one) and `freeable` anymore, just `tag` (and potentially `generate`) would be good enough?

My preference for how `tag` would work is like this:
1. check that the `deved` version of the package has everything committed
2. create a new branch called `release-3.5.2` in the deved repo (assuming that is the version that is going to be tagged)
3. set the version field in `Project.toml` in the deved folder to `3.5.2` and commit that to branch `release-3.5.2`.
4. compute and store for later the tree hash for this commit
5. set the version field in the deved folder to `3.5.3-DEV` (i.e. increment the patch version by one and add `-DEV`)
6. commit that also to the `release-3.5.2` branch
7. push the `release-3.5.2` branch (I guess to `origin`? I.e. we assume one has push access to the repo of the package)
8. Open a PR on the repo for the package for the branch `release-3.5.2`.
9. automatically figure out in which of the registries that the user has locally the package is registered and then do everything in that registry (or use an optional registry selection if the user specified one)
10. I'm not super clear about this step: a) create a new branch in the local registry repo `tag-packagename-3.5.2`, b) update all the files in the registry repo that need to be updated, c) commit, d) create a fork of the registry repo if needed, e) push the `tag-packagename-3.5.2` branch to the fork, f) open a PR for the branch `tag-packagename-3.5.2`, g) switch the local registry repo back to `master`.

I think at that point `tag` should stop. Now we wait for the registry PR to get merged.

At this point it would be nice if the following happened when the registry PR is merged: a) the PR for branch `release-3.5.2` is merged in the package repo, b) a tag is added to the package repo for version `3.5.2`. Both of these would require some sort of bot, or maybe it could be done with a github action, or something? Unclear to me... I think the tag adding could also be done via something like `PkgDev.check_all_tags(pkg_name)`, where it would just look through all the registered versions and add tags locally to the package.

**Comment by davidanthoff** [comment]
Just a heads up: I've started working on this and got pretty far. Not yet ready to put here, but I'm getting there.

**Comment by rofinn** [comment]
I know there was some discussion about moving `https://github.com/JuliaRegistries/Registrator.jl/tree/master/src/regedit` out and into a separate package that PkgDev could use. Would that still make sense with the work you've done @davidanthoff?

**Comment by davidanthoff** [comment]
Yes, very much! For now I'm taking a dependency on Registrator.jl and calling the code in there, but it would of course be much nicer if that was a lighter dependency.
