### ISSUE TITLE
ERROR: Unexpected character @ after scheme

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaLang/PkgDev.jl#157]
When using ssh remotes, the `get_repo_onwer_from_url` function fails with the above error.
Example:
```julia
julia> pkg_url = LibGit2.url(pkg_remote)
"git@github.com:SebastianM-C/SDFReader.jl.git"
julia> PkgDev.get_repo_onwer_from_url(pkg_url)
ERROR: Unexpected character @ after scheme
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] parse_url(::String) at /home/sebastian/.julia/packages/URIParser/Eg6Q9/src/parser.jl:216
 [3] Type at /home/sebastian/.julia/packages/URIParser/Eg6Q9/src/parser.jl:298 [inlined]
 [4] get_repo_onwer_from_url(::String) at /home/sebastian/.julia/packages/PkgDev/oJ4V7/src/PkgDev.jl:16
 [5] top-level scope at REPL[25]:1
```
whereas with https
```julia
julia> PkgDev.get_repo_onwer_from_url("https://github.com/SebastianM-C/SDFReader.jl")
"SebastianM-C/SDFReader.jl"
```

**Comment by davidanthoff** [comment]
I think it will in general be tricky to get things to work with ssh repos, there are quite a few other bits and pieces in this code that require a personal access token for github stored in the git credential manager, and I think if that is already the case, you might as well use https remotes in the first place?

**Comment by SebastianM-C** [comment]
I see. In that case maybe an error should be thrown if a ssh repo is added indicating that this is not supported?

**Comment by davidanthoff** [comment]
Yes, that is a good idea!

**Comment by davidanthoff** [comment]
Ok, fixed on master (I.e. better error message). I'll wait with a tag until there are some more features.
