### ISSUE TITLE
PkgDev.publish(): `no auth sock variable`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/PkgDev.jl#16]
I've got the following error when trying to push a tag.

```
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing Compat permanent tags: v0.7.7
ERROR: GitError(Code:ERROR, Class:SSH, error authenticating: no auth sock variable)
 [inlined code] from ./libgit2/error.jl:96
 in push at ./libgit2/remote.jl:84
```

The METADATA commit is created (not pushed) and tag is not pushed (to Compat.jl).

`versioninfo()` (yesterday master)
```
Julia Version 0.5.0-dev+848                                                       
Commit 0d1ea71* (2015-10-18 15:28 UTC)                                            
Platform Info:                                                                    
  System: Linux (x86_64-unknown-linux-gnu)                                        
  CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz                                  
  WORD_SIZE: 64                                                                   
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)                            
  LAPACK: libopenblas                                                             
  LIBM: libopenlibm                                                               
  LLVM: libLLVM-3.7.0                                                             
```

On `PkgDev` master.

C.c @jiahao who have seen the same problem.

**Comment by wildart** [comment]
Do you have ssh-agent running? Do you have `git` user and `IdentityFile` configured for `github.com` in `.ssh/config`?

**Comment by yuyichao** [comment]
I have nothing special configured for github (it's using my default ssh key) and there's no ssh-agent running.

Are these the new requirements to use `PkgDev` functions?
`git push` for `.julia/v0.5/Compat` and `.julia/v0.5/METADATA` works without any additional steps and this also works on 0.4 so I think it should be working on 0.5 with PkgDev as well.

**Comment by tkelman** [comment]
Your `git` has ssh support, libgit2 probably does not. What is `git remote -v` for those repos?

**Comment by yuyichao** [comment]
```

**Comment by yuyichao** [comment]
FWIW, my `libgit2` does link to `libssh2`

```
yuyichao% ldd /usr/lib/libgit2.so.0.23.2 
        linux-vdso.so.1 (0x00007ffdd25fe000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007feef83ac000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007feef8196000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007feef7f1c000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007feef7aa4000)
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007feef7878000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007feef7670000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007feef7452000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007feef70ae000)
        libidn.so.11 => /usr/lib/libidn.so.11 (0x00007feef6e7a000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007feef6c2c000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007feef6947000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007feef6716000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007feef6511000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007feef630d000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x0000559b86ec6000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007feef60ff000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007feef5efb000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007feef5ce4000)
```

**Comment by wildart** [comment]
If I think it's relates to `ssh-agent` authentication pathway in credentials callback. In general, you should get a prompt, that asks bunch of info (user, key location, key pass), when doing ssh authentication.

**Comment by yuyichao** [comment]
> user, key location, key pass

Even when the user is encoded in the `git+ssh` url, the key location is the default one (`~/.ssh/id_rsa`) and the key file doesn't have a password?

**Comment by wildart** [comment]
Officially, we are supporting ssh, so I didn't do much work on ssh default credentials (payload) for an authentication callback. Just covered https.

**Comment by yuyichao** [comment]
> we are supporting ssh

You mean we are not?

So right now what should be the fix?

**Comment by wildart** [comment]
Surely, we don't officially support ssh protocol in the .package manager (fixed above).

As of above problem, it's some where in the [credential_callback](https://github.com/JuliaLang/julia/blob/c510114be12ce836befdceacd06f66a28a3db069/base/libgit2/callbacks.jl#L33-L101).

It would be better to move all ssh related code in `PkgDev`, and, in `PkgDev`, select callbacks based on a remote protocol.

**Comment by tkelman** [comment]
> It would be better to move all ssh related code in `PkgDev`

Agreed. I doubt it's easily possible, but since ssh should be optional it would be cool to somehow deal with ssh dynamically as a plugin here even if the libgit2 c library is built without ssh headers present at build time.

**Comment by wildart** [comment]
Then we need to provide some kind of alias or variable in `LibGit2` for binary library switching.

**Comment by tkelman** [comment]
That might be a good idea to do anyway.

I doubt LibGit2 is designed this way, but in a perfect world we could hypothetically supply an ssh lib at runtime and somehow enable it for use with an existing libgit2 library that didn't have ssh support at build time. Essentially what we're going to have to do for mbedtls, also for ssh.

**Comment by wildart** [comment]
Not relevant anymore, as we support `ssh` in `LibGit2`. However, I would discourage use of `ssh` for METADATA publishing in `PkgDev` operations.
