### ISSUE TITLE
Merge with PkgTemplates into a new package in the long run?

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/PkgDev.jl#168]
As I've stated in https://github.com/invenia/PkgTemplates.jl/issues/144 already, I think it would be good to consider merging both packages into a new one since they increasingly overlap (which is a good thing because it leads towards more complete solutions). For more points, see the referenced issue.

**Comment by davidanthoff** [comment]
I'll close this issue here, lets have the discussion in the other issue.
