### ISSUE TITLE
tag() doesn't change anything in METADATA when package isn't registered

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/PkgDev.jl#20]
When calling `PkgDev.tag()` on a package that isn't registered in METADATA (neither locally or remotely), the tag is correctly created, but nothing else happens. This goes completely against the docs, and is really disturbing. Better raise an error.

The messages look like this:

``` julia
julia> PkgDev.tag("FreqTables")
INFO: Tagging FreqTables v0.0.1
```

**Comment by wildart** [comment]
That's a bug. We shouldn't tag unregistered package at all.

**Comment by Keno** [comment]
:+1:

**Comment by wildart** [comment]
Correction, my previous statement was incorrect. An unregistered package can be tagged and no record to METADATA is added. So is there a problem with such behavior? I do not see any.

**Comment by tkelman** [comment]
Making a git tag and no metadata tag isn't a very useful operation. Usually this would happen if someone did tag and register in the wrong order.

**Comment by wildart** [comment]
What it I do not what to register a package for now, but would like to tag my progress with versions?

**Comment by tkelman** [comment]
Tag via either command-line git or libgit2, not PkgDev.
