### ISSUE TITLE
suggest Pkg.unregister(), Pkg.unmaintain()

### ISSUE THREAD

**Issue by J-Sarnoff** [JuliaLang/PkgDev.jl#21]
There are a number of packages listed at http://pkg.julialang.org/ that are no longer maintained written by people who would like to mark them as unmaintained or remove them from the list.
Pkg.unmaintain(), Pkg.unregister() where those commands were only executable by the package author/maintainer would allow contributors to offer a cleaner package ecosystem.
They could accept a version number as an optional second argument.

The current system does not serve the a package author who prefers not to change METADATA. Nor does it support an author who no longer feels their old code should be available even for an older version of Julia.  If setting the upper Julia version number to 0.0.0 or 0.0.1 would have the effect of erasing a Package, then there should be command automating that for the author/maintainer.  

This suggestions stems from wanting to give people with the background and desire to offer a package to the community an eventual UNDO or NoMoreDoing, should that become their preference.  It seems to me this would add to the welcome Julia extends to package contributors.

**Comment by tkelman** [comment]
It should be called deprecate if we add this feature. x-ref https://groups.google.com/forum/#!topic/julia-dev/oovY1igqYK4 and https://github.com/JuliaLang/METADATA.jl/issues/347#issuecomment-35015012.

**Comment by hayd** [comment]
There should also be an option for the community (or a particular person) to fork and take over, rather than just delete completely. Some kind of purgatory.

**Comment by J-Sarnoff** [comment]
agreed

**Comment by wildart** [comment]
There is no way to delete completely anything from git repo. If it's there, it stays there.

However, I fill this issue belong to METADATA.jl, not here. This package is merely follows METADATA standard.

**Comment by tkelman** [comment]
Well this package is about automating certain metadata modifications. So a helper function that goes and adds upper julia versions on all past tags would be reasonable I think.
