### ISSUE TITLE
Pkg.submit not working on Windows?

### ISSUE THREAD

**Issue by KrisDM** [JuliaLang/PkgDev.jl#26]
I made some changes to a package (on my own branch, as suggested in the documentation). I did a commit, filled out a commit message in vim and after saving that and attempting to submit I get the following:

```
julia> Pkg.submit("PDMats")
INFO: Forking JuliaStats/PDMats.jl to KrisDM
ERROR: could not spawn `curl --version`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```

There was a similar problem mentioned here:
https://github.com/JuliaLang/julia/issues/5937

But that solution did not work for me (I don't seem to have .julia/v0.4/.github/token).

**Comment by tkelman** [comment]
Right, we need to write alternate versions of the code that interacts with the github api that doesn't use curl for julia 0.5 on windows. Can probably go via invoke-restmethod and similar in powershell.

On 0.4 I think this is also broken by my path changes and should be fixable with a few small tweaks, can you open a base issue for 0.4 so I remember to fix it before 0.4.4?

**Comment by yuyichao** [comment]
Does this package even [support 0.4](https://github.com/JuliaLang/PkgDev.jl/blob/0f987b4d448f37999b2d94599b6b07de355b391f/REQUIRE#L1) ?

**Comment by tkelman** [comment]
No but the code that was run above used `Pkg.submit` which must have been in 0.4 rather than using this package. Valid issue on both, but with different solutions.

**Comment by bjarthur** [comment]
i'm getting the same `curl --version` error on julia 0.6, despite the same command working just fine in git-bash.
