### ISSUE TITLE
Add tests for PkgDev.register

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/PkgDev.jl#27]
and any other auth-required tests if we can figure out the right way to do them

**Comment by tkelman** [comment]
whatever caused 3dc3c131b6c8b58abd0e2a6aa86282641716814e should have a test too if possible

**Comment by Keno** [comment]
Pkg.tag

**Comment by tkelman** [comment]
right which there are tests for, but not on a registered package from what I can tell

**Comment by wildart** [comment]
Sorry, that was my bad.
