### ISSUE TITLE
Remove dependency on `curl`

### ISSUE THREAD

**Issue by wildart** [JuliaLang/PkgDev.jl#30]
Currently, interaction with GitHub API requires `curl` to be installed. It would be nice to remove this dependency an use [Requests.jl](https://github.com/JuliaWeb/Requests.jl).

**Comment by nalimilan** [comment]
How does Requests.jl fare as regards proxies and other special network configurations on Windows?

**Comment by wildart** [comment]
Reuqests.jl supports proxy. Any issues can be addressed with that package.

**Comment by tkelman** [comment]
Requests also requires binary dependencies. It would be easier on windows to just use powershell.

**Comment by tkelman** [comment]
And the web stack has a tendency of getting broken by changes to Julia master. Ideally we'll hook up regular runs of PkgEval to identify these situations and fix them faster, but on platforms where curl is reliably present we know it's not going to break. For infrastructure things like PkgDev, Coverage, etc I don't think it's a good idea to make them depend on the Julia web stack right now. We can add a little bit of code to handle portability, we can't guarantee the web stack will work on Julia master at all times - short of running "critical packages" tests as part of base Julia's CI, which isn't feasible right now.

**Comment by wildart** [comment]
Right. There are a lot of pieces missing in `Requests`, that would require to be on a level with `curl`. Nevertheless, it is a good goal. As for web stack, it's a pity that it hasn't event same priority as JuliaOpt or JuliaStat.
