### ISSUE TITLE
Cannot access Github via ssh

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/PkgDev.jl#34]
I like to use an ssh url for Github repos (such as `git@github.com:eschnett/FlexibleArrays.jl.git`) because this allows me to store my password in a keychain, so that I don't have to type it in every time. This used to work fine in the past.

I now find that Julia cannot access Github via ssh any more, and I have to use the https protocol. This is both for reading and writing, even for read-only access to a public repository.

If this is a configuration error on my side, I apologize, but I don't recall configuring things in a particular way. Alternatively, if there is a way to set up a keychain for https, that would also be fine.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13899

**Comment by yuyichao** [comment]
And https://github.com/JuliaLang/PkgDev.jl/issues/16
