### ISSUE TITLE
RFC: Julia Package Manifest File

### ISSUE THREAD

**Issue by wildart** [JuliaLang/PkgDev.jl#37]
Following discussion in on extended package manifest file [julia/#11955](https://github.com/JuliaLang/julia/issues/11955). I started to work on specifying content of such manifest file in the `manifest` branch.

Package manifest documentation file, [MANIFEST.md](https://github.com/JuliaLang/PkgDev.jl/blob/manifest/MANIFEST.md), includes description of the fields and some thoughts on changes in work of the package manager.

@StefanKarpinski @IainNZ

**Comment by ararslan** [comment]
If the types for specifying Julia and dependency requirements are all string, how could one specify upper and lower bounds on versions? For example, JuliaStats/TimeSeries.jl currently *only* supports Julia 0.4, so it has an inclusive lower bound at 0.4 and an exclusive upper bound at 0.5-. Is there a way to specify this in your proposition?

Similarly, some packages have platform-specific dependencies, usually Homebrew on OS X and WinRPM on Windows.

(Apologies if this is all obvious and I've overlooked something.)
