### ISSUE TITLE
PkgDev.publish() seems to be broken

### ISSUE THREAD

**Issue by phobon** [JuliaLang/PkgDev.jl#38]
On both latest Julia and PkgDev:

```
julia> PkgDev.publish()
ERROR: MethodError: no method matching find_in_path(::SubString{UTF8String}, ::ASCIIString)
Closest candidates are:
  find_in_path(::Union{ASCIIString,UTF8String}, ::Any)
 in dir(::SubString{UTF8String}) at /home/jdlangs/.julia/v0.5/PkgDev/src/PkgDev.jl:21
 in (::PkgDev.Entry.##4#7{ASCIIString})(::Base.LibGit2.GitRepo) at /home/jdlangs/.julia/v0.5/PkgDev/src/entry.jl:69
 in with(::PkgDev.Entry.##4#7{ASCIIString}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:565
 in publish(::ASCIIString, ::ASCIIString) at /home/jdlangs/.julia/v0.5/PkgDev/src/entry.jl:51
 in publish() at /home/jdlangs/.julia/v0.5/PkgDev/src/PkgDev.jl:58
 in eval(::Module, ::Any) at ./boot.jl:236
```

**Comment by tkelman** [comment]
tagged version or master of PkgDev?

**Comment by phobon** [comment]
master

**Comment by wildart** [comment]
Do you have recent julia master? What `PkgDev.dir("PkgDev")` reports?

**Comment by phobon** [comment]
Yes, this was on today's nightly build. `PkgDev.dir("PkgDev")` gives what I assume is the expected output: `"/home/jdlangs/.julia/v0.5/PkgDev"`

The same error shows up for the tagged version of `PkgDev` too so presumably it's from some recent julia change.

**Comment by tkelman** [comment]
could use a bisect on julia then, I suppose?

**Comment by phobon** [comment]
Sure, I can probably do that in a few hours.

**Comment by wildart** [comment]
My nightly build works fine.
```
Julia Version 0.5.0-dev+3669
Commit 17dfdc1* (2016-04-21 15:28 UTC)
```

**Comment by phobon** [comment]
Did the bisect and found the breaking commit: https://github.com/JuliaLang/julia/commit/ad370215297c3d78efd9b1135f7731b115c2ccc7

**Comment by tkelman** [comment]
Aha. Do you have unicode in your username, or is this maybe an inference issue?

**Comment by tkelman** [comment]
nevermind, SubString
