### ISSUE TITLE
Pkg.rm removes the package, but keeps it in the session cache

### ISSUE THREAD

**Issue by nashjain** [JuliaLang/PkgDev.jl#4]
Example:

julia> Pkg.clone("https://github.com/johnmyleswhite/MySQL.jl.git")
INFO: Cloning MySQL from https://github.com/johnmyleswhite/MySQL.jl.git
INFO: Computing changes...

julia> using MySQL
ERROR: DBI not found
 in require at loading.jl:47
 in include at /Applications/Juno.app/Contents/Resources/app/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Juno.app/Contents/Resources/app/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/naresh/.julia/v0.3/MySQL/src/MySQL.jl, in expression starting on line 2

julia> Pkg.clone("https://github.com/JuliaDB/DBI.jl.git")
INFO: Cloning DBI from https://github.com/JuliaDB/DBI.jl.git
INFO: Computing changes...

julia> using MySQL

---
Now

julia> Pkg.rm("DBI")
INFO: Removing DBI (unregistered)

julia> using MySQL

Should have not worked...

julia> Pkg.resolve()
INFO: No packages to install, update or remove

julia> using MySQL

Makes no difference 

julia> exit(0)

Exited the session and after coming back...

julia> using MySQL
ERROR: DBI not found
 in require at loading.jl:47
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/naresh/.julia/v0.3/MySQL/src/MySQL.jl, in expression starting on line 2

**Comment by yuyichao** [comment]
AFAIK this is the expected behavior, if the module is already loaded, it won't disappear because the underlying file is gone.

Also this is the wrong place to report issue to the base `Pkg.*` functions.
