### ISSUE TITLE
`Pkg.publish()` push permanent tags [even if it exists] to source-code-server

### ISSUE THREAD

**Issue by kuldeepdhaka** [JuliaLang/PkgDev.jl#41]
```
INFO: Validating METADATA
INFO: Pushing Box0 permanent tags: v0.1.0
Username for 'https://gitlab.com': kuldeepdhaka
Password for 'https://kuldeepdhaka@gitlab.com': 
INFO: Submitting METADATA changes
INFO: Forking JuliaLang/METADATA.jl to kuldeepdhaka
INFO: Recompiling stale cache file /home/kuldeep/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/kuldeep/.julia/lib/v0.4/JSON.ji for module JSON.
INFO: Pushing changes as branch pull-request/1a333930
INFO: To create a pull-request, open:

  https://github.com/kuldeepdhaka/METADATA.jl/compare/pull-request/1a333930
```

but, the `v0.1.0` annotated tag existed on the source-code-server (so, **no** push is required).
i was required to provide credentials or it won't proceed.

**Comment by wildart** [comment]
sorry, `gitlab` repos are not supported

**Comment by wildart** [comment]
How did you manage to tag commit in remote repo?

**Comment by kuldeepdhaka** [comment]
> How did you manage to tag commit in remote repo?
Because i mantain it.
`git tag -a v0.1.0` (for latest commit) and `git push v0.1.0`

> Pkg.publish suppose to push all tags to remote repo, and because your repo is hosted on GitLab, you've been asked for credentials.
But the tags are already on server. im just require to enter credentials for already done task.

**Comment by wildart** [comment]
Currently, there is no check if the tag exists in the remote tracking branch. `PkgDev.tag` call assumes that no tags were created before and creates it, and `PkgDev.publish` pushes it to remote repo. It was done deliberately, so user would not version package with `git` tool, as you did.

We try to discourage use of `git` tool. That is why `PkgDev` package was created - to spare user from third party tools and provide instead set of instruments which would consistently perform common activities on packages.

If you want perform these actions without help of `PkgDev`, you can do so. However, make sure that you are responsible for the result, and that your actions could undermine existed functionality of  `PkgDev`. Please, consult documentation before you undertake any action.

**Comment by tkelman** [comment]
How much code would it be to add a check for existing tags first, throw an error when things conflict? It's somewhat against the current design, but we might take a PR that added a check.

**Comment by wildart** [comment]
I do not know, checking an existence of a remote tag it is not trivial.
