### ISSUE TITLE
PkgDev has no versions that support 0.4.5 of julia

### ISSUE THREAD

**Issue by leclere** [JuliaLang/PkgDev.jl#44]
I'm not sure its an issue or if I am misunderstanding the way the package should work. When I call 
Pkg.add("PkgDev") (just after calling Pkg.update()) I obtain

ERROR: PkgDev can't be installed because it has no versions that support 0.4.5 of julia. 
You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at ./pkg/entry.jl:410
 in edit at pkg/entry.jl:26
 in anonymous at task.jl:447
 in sync_end at ./task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

**Comment by timholy** [comment]
`PkgDev` was split out from julia during the development of julia-0.5. So it's basically already "there" on julia-0.4, inside `Pkg`.

Since this wasn't clear, it would be very helpful if you'd edit whatever documentation led you to think you needed `PkgDev`. (One thing to note, though: if you're reading the julia manual, make sure you select the version appropriate for the version of julia you're using.)

**Comment by wildart** [comment]
`PkgDev` targets julia-0.5. It is quite strange that you were able to install it on julia-0.4. Who did it happen?

**Comment by nalimilan** [comment]
I get this all the time too. It's just that you can install it from 0.5, and then 0.4 sees it if you use the same directory. But AFAICT it's completely harmless.

**Comment by tkelman** [comment]
> if you use the same directory.

Well there's yer problem? Either someone suggested trying to install PkgDev on 0.4, or someone suggested using the same package directory for multiple versions of Julia. Neither are recommended.

**Comment by nalimilan** [comment]
Ah, sorry, I hadn't noticed the OP actually tried to install PkgDev, which obviously should fail. My "problem" isn't really one since everything works (even if that configuration isn't recommended).

**Comment by leclere** [comment]
Yeah, I will try to find the recommandation I tried to follow. Actually I am developping a package (optimization oriented) for julia. I was looking for the easiest way to add it to METADATA.jl, and found a link to PkgDev which failed. 

I will look back in the documentation I read to see if it was specified for julia 0.5. In the meantime if someone can point me toward the best way of adding my package to METADATA.jl from julia 0.4.5 that would be great.

Thanks anyway.

**Comment by tkelman** [comment]
Replace `PkgDev` with just `Pkg` for 0.4, everything else should be equivalent.

**Comment by leclere** [comment]
Ok thanks, my mistake was to think that "latest" in the juliadoc refered to the 4.5 version and not the 5.0. I close the "issue".

**Comment by timholy** [comment]
@leclere, that's an excellent point: "latest" is indeed confusing. It should probably be replaced with "devel" or "alpha" or something.
