### ISSUE TITLE
Missing common license types?

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaLang/PkgDev.jl#46]
I can only imagine that not having GPL{2, 3} as one of the options is a not so subtle way of discouraging these licenses, but a fair number of packages will want to use this license (being based on R lets say, or many other common sources). Should this not be a supported option? Having code report the wrong license because the tooling is opinionated seems odd to me.

**Comment by ivarne** [comment]
Ref: https://github.com/JuliaLang/julia/issues/4908

**Comment by tkelman** [comment]
Actually we should probably close that one since `Pkg.generate` is here and not in base any more.
