### ISSUE TITLE
Pkg.generate inside a pre-existing repo

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/PkgDev.jl#49]
If I have a git repo that I want to turn into a package, `Pkg.generate` should generate the appropriate files inside that repo, and copy everything over to `.julia`; currently this needs to be done by hand.
Related to #8

**Comment by ivarne** [comment]
Moved from https://github.com/JuliaLang/julia/issues/17042 (Because I think everyting should be linked.)

**Comment by wildart** [comment]
You should play with `LOAD_PATH` for setting your development environment. I strongly oppose development in `.julia` folder. It is supposed to be the cache of dependencies not a project folder.

**Comment by KristofferC** [comment]
I think that packages in `.julia` take precedence if you have a package of the same name in `LOAD_PATH`. Maybe this should be reversed.

**Comment by wildart** [comment]
I want that a lot. But this is not a solution. I hope to decouple PkgDev commands from `.julia` folder, so you can run `PkgDev` commands from any directory.
