### ISSUE TITLE
Ability to publish different branches?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/PkgDev.jl#57]
This is admittedly likely to affect only a small number of people, but I wonder about whether it's reasonable to support `publish`ing branches that are not `metadata-v2`. Now that I'm back working on packages, I often have 3 or more simultaneous PRs in to METADATA, and to avoid duplication I create separate branches. Even if we get to the point where Travis isn't the bottleneck in METADATA PRs, it's been demonstrated repeatedly that these PRs are still worth reviewing, so it seems likely that many PRs will be out there for at least several hours.

**Comment by tkelman** [comment]
I actually think we should adjust the sequence here to create a new branch before tagging.
