### ISSUE TITLE
Pkg.autoload("Package") ?

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/PkgDev.jl#59]
I was wondering if this had been discussed somewhere. I know some people are concerned that a lot of "core" (in a scientific not programming language way) functionality is being moved out of base. Prime number functionality could be such an example. Some people seem to be annoyed that they have to load stuff like Plots.jl or Primes.jl every time they run Julia. Would it make sense for Pkg to have a function that added the proper lines to the proper files on the different platforms, such that `julia`in the terminal would `using A, B, C, ...` where A, B and C had been passed to `Pkg.autoload()`?

Not really sure if this is the right place to ask, but Pkg discussions seem to happen here.

**Comment by tkelman** [comment]
It's called juliarc.

**Comment by aviks** [comment]
Documentation about .juliarc is here:
http://docs.julialang.org/en/release-0.4/manual/getting-started/?highlight=juliarc

This is the recommended way to do what you propose. It is also flexible enough to satisfy many other use cases.
