### ISSUE TITLE
Documentation hosting

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/PkgDev.jl#6]
We need to host a long form of the documentation (not just docstrings) somewhere, Read the Docs?

cc @tkelman

**Comment by tkelman** [comment]
Thanks for opening this, good to track here.

Sims.jl is hosted on Mkdocs which looks quite nice and doesn't have to go through sphinx, not clear how much work it is to set up https://tshort.github.io/Sims.jl/

@MichaelHatherly do you have any recommendations on this?

**Comment by MichaelHatherly** [comment]
The https://github.com/MichaelHatherly/Docile.jl/tree/rewrite branch of Docile has some support for documentation generation (x-refs, embedded examples, doctests). I'm not quite finished with it yet though, but it has been used to generate it's own docs which seems to work well enough.

Regarding hosting the resulting docs I've just been using the repo itself for hosting and viewing. I'm sure for many packages just a README file is all that's really needed. Though, of course, hosting elsewhere may be better suited for other packages. Docile's markdown output should be agnostic enough to allow people to host their docs wherever they'd like I think.
