### ISSUE TITLE
When tagging, check that commit has changed

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/PkgDev.jl#62]
When creating a new tag using `tag`, something should happen—ideally an error, or at least a warning—when the commit SHA used for the tag matches that of another tag. I was bitten by this recently when tagging a couple of JuliaStats packages.

Apparently this is already a to-do item, since it's [mentioned in a comment](https://github.com/JuliaLang/PkgDev.jl/blob/master/src/entry.jl#L246), but I figured it would be worth submitting an issue to track it.

**Comment by martinholters** [comment]
...but in case I'm so happy with my 0.35.3 version that I decide to finally call it 1.0.0, I should be able to do so, using `force=true` or whatever.

**Comment by tkelman** [comment]
Yes, definitely either make this a warning or have a way of getting around it for cases like re-tagging the same thing with a different minor/major.
