### ISSUE TITLE
issues with Pkg.submit()

### ISSUE THREAD

**Issue by musm** [JuliaLang/PkgDev.jl#66]
On windows and using v0.5rc2 and I checkout out the latest PkdDev.

I'm following the steps as directed here http://docs.julialang.org/en/latest/manual/packages/#man-post-hoc-branching. 

The problem: I do PkgDev.submit("Foo")  it ignores the current branch name `fixdepwarn` that I created and creates an arbitrary branch name `pull-request/fb12215b`. I go the the url it says to open for the pull request. Thus far no problem other than the fact that it ignored my branch name.

Now I make additional changes to my local repo on my computer to update the PR and then do `git push` this gives the error

```
fatal: The current branch fixdepwarn has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin fixdepwarn
```

I look at `git remote -v` and I see origin set at the  package owner's git address. Despite the fact that it forked the repo to my github page,  I do not see my git address as a remote. Thus I have to force it to my repo via `git push git@github.com:musm/Foo.jl.git fixdepwarn:pull-request/fb12215b`

**Comment by wildart** [comment]
Known issue, see #13.
