### ISSUE TITLE
Disable Codecov Github comments in new packages

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/PkgDev.jl#68]
By default, Codecov adds Github comments each time it runs. This usually just adds noise to the discussion. See e.g. <https://github.com/JuliaLang/IterativeSolvers.jl/pull/80>.

This can be avoided by adding a `.codecov.yml` file to newly generated packages. See the pull request above for such a configuration.

With this change, Codecov's results continue to be available in pull requests as a single coloured icon that leads to the respective Codecov page with the detailed results.

**Comment by tkelman** [comment]
seems fine when coverage is selected. the addition of more boilerplate files is getting annoying, but unless they change their mind about defaulting to "spam on" then not much we can do.

**Comment by KristofferC** [comment]
Incredibly annoying change by them...
