### ISSUE TITLE
GitError on `PkgDev.publish()`

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/PkgDev.jl#69]
I have no idea what is causing this. I just set up a new machine (Ubuntu 16.04) and I'm getting this on Julia 0.5-rc2:

```
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing TypedTables permanent tags: v0.1.2
ERROR: GitError(Code:EAUTH, Class:OS, The ProgramData file 'config' doesn't exist: )
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /home/ferris/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

**Comment by malmaud** [comment]
I got this too on rc2

**Comment by wildart** [comment]
try to run `PgkDev.config()`

**Comment by jakebolewski** [comment]
Shouldn't the error message be changed to suggest that?

**Comment by andyferris** [comment]
I have run `PkgDev.config()` but apart from stating the obvious it didn't do anything to solve the EAUTH problem.

**Comment by malmaud** [comment]
Didn't help me either

**Comment by dlfivefifty** [comment]
Me neither.

**Comment by andyferris** [comment]
I just noted that this is still an issue on Julia 0.5-rc3... I had figured it would be fixed with the other firewall/curl changes in Julia. But maybe there is something else broken. It did work fine on rc1.

**Comment by andyferris** [comment]
Oh... I just noticed the error message is a little different:

``
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing CoordinateTransformations permanent tags: v0.3.2
ERROR: GitError(Code:EAUTH, Class:None, No errors)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /home/ferris/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

**Comment by Evizero** [comment]
Experiencing same issue as last post on OSX 10.11.5 with RC4

**Comment by tkelman** [comment]
> It did work fine on rc1.

Did it work on rc2? To narrow it down at least.

**Comment by andyferris** [comment]
Not for me... broken on rc2+1, rc3 and rc4 but working on rc1. I was building Julia myself, but I just confirmed the same issue on the downloaded linux binaries for rc4 so I don't think that is the issue.

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc4+0 (2016-09-09 01:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using PkgDev
INFO: Recompiling stale cache file /home/ferris/.julia/lib/v0.5/PkgDev.ji for module PkgDev.

julia> PkgDev.tag("StaticArrays")
INFO: Tagging StaticArrays v0.0.6
INFO: Committing METADATA for StaticArrays

julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing StaticArrays permanent tags: v0.0.6
ERROR: GitError(Code:EAUTH, Class:None, No errors)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /home/ferris/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

**Comment by andyferris** [comment]
OK I've gone back and made another rc1 build... but now it doesn't work with an error I haven't seen yet ("syscall failure"):

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc1+0 (2016-08-04 08:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> using PkgDev
INFO: Recompiling stale cache file /home/ferris/.julia/lib/v0.5/PkgDev.ji for module PkgDev.
INFO: Recompiling stale cache file /home/ferris/.julia/lib/v0.5/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/ferris/.julia/lib/v0.5/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /home/ferris/.julia/lib/v0.5/JSON.ji for module JSON.

julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing StaticArrays permanent tags: v0.0.6
Username for 'https://github.com':andyferris
Password for 'https://andyferris@github.com':
ERROR: GitError(Code:ERROR, Class:OS, SSL error: syscall failure: )
 in macro expansion at ./libgit2/error.jl:98 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:179
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:645
 in publish(::String, ::String) at /home/ferris/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /home/ferris/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

Maybe something in the newer versions of *PkgDev* isn't compatable with rc1 anymore...

**Comment by tkelman** [comment]
That would surprise me. When you say "gone back" what level of clean did you do between builds?

**Comment by andyferris** [comment]
Oh bugger, you got me! I typed `make distclean` not `distcleanall` (even though I remembered I should do that...) I'll try again and see if its more sensible.

**Comment by andyferris** [comment]
OK, `make distcleanall` has the same issue as above. Oh well...

**Comment by ssfrr** [comment]
I think this (and #48) may be solved with @Keno's recent fix (#75). Try with PkgDev master and see if it's still a problem. I was getting the same `EAUTH` error as @andyferris's problem [above](https://github.com/JuliaLang/PkgDev.jl/issues/69#issuecomment-245800950) and it works on PkgDev master.

Also - should one of these issues be closed as a dup? It seems like at the end both issues have the same `ERROR: GitError(Code:EAUTH, Class:None, No errors)` error (aside from the weirdness with 0.5-rc1, but that doesn't seem like a big problem)

**Comment by felipenoris** [comment]
`PkgDev` master branch worked for me.

**Comment by cstjean** [comment]
Worked for me too.

**Comment by KristofferC** [comment]
Works for me too.

**Comment by dpo** [comment]
Not for me. PkgDev master still gives me
```
ERROR: GitError(Code:EAUTH, Class:None, No errors)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /Users/dpo/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /Users/dpo/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish(::String) at /Users/dpo/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

**Comment by andyferris** [comment]
It works for me! Thanks

I'm ready to close this issue except for @dpo has an error. @dpo, would you like to create a new issue for your error since the majority of cases here are solved and your case might be more specific somehow? I will close this one now.

**Comment by tpoisot** [comment]
I had the same issue, solved it with `PkgDev.GitHub.token()` to create a token. Worked after that.

**Comment by leclere** [comment]
On branch master, PkgDev.publish() give me the following error:

WARNING: The explicitly provided credentials were incompatible with the server's supported authentication methods
ERROR: GitError(Code:EAUTH, Class:OS, The ProgramData file 'config' doesn't exist: )

P.S: if someone tell me how to post a complete output in a nice format I can give a more complete one.
