### ISSUE TITLE
GitError(Code:ERROR, Class:Net, Unsupported URL protocol)

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/PkgDev.jl#7]
I don't understand what the resolution of the discussion about `git` versus `https` protocols was.
I'm getting the following (newly `pull`ed and compiled Julia master; v0.1.0 of `PkgDev`):

```
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing CRlibm permanent tags: v0.2.0
ERROR: GitError(Code:ERROR, Class:Net, Unsupported URL protocol)
 [inlined code] from libgit2/error.jl:96
 in __push#333__ at libgit2/remote.jl:84
 [inlined code] from essentials.jl:116
 in __push#353__ at libgit2.jl:178
 [inlined code] from essentials.jl:116
 in anonymous at /Users/davidsanders/.julia/v0.5/PkgDev/src/entry.jl:99
 in with at ./libgit2/types.jl:481
 [inlined code] from libgit2/types.jl:487
 in publish at /Users/davidsanders/.julia/v0.5/PkgDev/src/entry.jl:84
 in publish at /Users/davidsanders/.julia/v0.5/PkgDev/src/PkgDev.jl:55
```

The package is a fresh copy with `Pkg.add("CRlibm")` and then `Pkg.checkout()`, which gives:

```
19:03 $ git remote -v
origin  git://github.com/dpsanders/CRlibm.jl.git (fetch)
origin  git@github.com:dpsanders/CRlibm.jl.git (push)
```

**Comment by jakebolewski** [comment]
The git protocol is simply not supported with libgit2.  I would not use 0.5-dev to do serious work. At some point all of METADATA.jl will be switched over to use https:// before 0.5 is released.

**Comment by tkelman** [comment]
Did you have `CRlibm` previously installed, and possibly moved to your `.trash` ? `Pkg.rm` doesn't actually delete the package, there are a few issues open on that. The `git@github.com:dpsanders` push remote needs ssh support, which we don't have enabled. I think if you do `rm(Pkg.dir("CRlibm"), recursive=true)` (be sure you don't have any important local changes or branches you haven't pushed yet) then `Pkg.add("CRlibm")` should hopefully clone it with a push-able https remote.

**Comment by wildart** [comment]
You could try `git remote set-url origin https://github.com/dpsanders/CRlibm.jl.git `.

**Comment by wildart** [comment]
#10
