### ISSUE TITLE
Accidentally adding ".jl" when tagging package will still tag package but leave out the METADATA commit

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/PkgDev.jl#70]
Ex:

```jl
julia> PkgDev.tag("NearestNeighbors.jl", :minor)
INFO: Tagging NearestNeighbors.jl v0.1.0

julia>
```

The tag is added but the METADATA commit is silently not happening. Should probably error or do both.

**Comment by tkelman** [comment]
same underlying issue as https://github.com/JuliaLang/PkgDev.jl/issues/20
