### ISSUE TITLE
PkgDev should run same validation as METADATA.jl Travis script before publishing

### ISSUE THREAD

**Issue by simonster** [JuliaLang/PkgDev.jl#72]
Ideally, the validation code should be part of PkgDev and METADATA should just install PkgDev and run it.

**Comment by tkelman** [comment]
Half of it already is. We could include the script from METADATA during publish here. I'd rather not move that policy-check code since then any adjustments to it would require tagging PkgDev to propagate to metadata.

**Comment by ssfrr** [comment]
The `Validating METADATA` step during `Pkg.publish()` already takes upwards of a minute to run on my machine, so I'd be sad if it got even slower.

**Comment by tkelman** [comment]
I think most of the time in https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/.test/METADATA.jl is the `check_metadata` step but haven't timed it too carefully. It doesn't take all that long on Travis, but might be considerably slower on Windows.
