### ISSUE TITLE
PkgDev.untag (https://github.com/JuliaLang/julia/issues/8289)

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/PkgDev.jl#76]
Moved from https://github.com/JuliaLang/julia/issues/8289 - this should only be allowed on tags that aren't yet merged to upstream METADATA, ones that are not yet published as part of an in-progress PR and need revision of some kind.

**Comment by ararslan** [comment]
Duplicate of #39?

**Comment by tkelman** [comment]
whoops, yeah

**Comment by tkelman** [comment]
and #73
