### ISSUE TITLE
Simplify the format of the generated license

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/PkgDev.jl#78]
Currently licenses generated from this package have a brief description at the top, then use markdown quoting to include the actual license text. The downside to this is that recently GitHub introduced a new UI feature that shows the type of license in the same banner as contributors and releases, but licenses formatted this way don't get automatically recognized by GitHub. It might be nice to simplify the formatting to plain text only.

As an example of what I mean, compare [the plain text license for Jackknife.jl](https://github.com/ararslan/Jackknife.jl/blob/master/LICENSE) with [the formatted license for this repo](https://github.com/JuliaLang/PkgDev.jl/blob/master/LICENSE.md). The former looks like this in the GItHub UI:

![screen shot 2016-09-29 at 2 00 53 pm](https://cloud.githubusercontent.com/assets/6396159/18972279/59a5e096-864d-11e6-8fd2-1f9a57fe4e5f.png)

and the latter:

![screen shot 2016-09-29 at 2 01 54 pm](https://cloud.githubusercontent.com/assets/6396159/18972291/6215dcea-864d-11e6-87b2-802e9cf7a32a.png)

GitHub UI changes aside, I actually think the plain text version looks a little nicer anyway, but that's just personal preference.

**Comment by tkelman** [comment]
Seems like we could also ask if github's license-detector can be made a bit smarter to figure out simple formatting.

**Comment by ararslan** [comment]
I would have suggested that if not for
> GitHub UI changes aside, I actually think the plain text version looks a little nicer anyway, but that's just personal preference.

😉

**Comment by Keno** [comment]
Just a matter of submitting a PR to https://github.com/benbalter/licensee.

**Comment by visr** [comment]
In the linked licensee issue above you can see our current version won't be accepted in licensee. So shall we go ahead with Alex' proposal instead?

[PkgTemplates.jl](https://github.com/invenia/PkgTemplates.jl) uses that format as well. With the small difference that the first line is not included, which conveniently gives the name of the license. This is included in the https://choosealicense.com/ format that both GitHub and GitLab use as templates.

**Comment by Nosferican** [comment]
I completely agree, but I think a more robust way would be to have the generated `project.toml` use a tag for license according to the SPDX license ID.
