### ISSUE TITLE
Interactive package generation

### ISSUE THREAD

**Issue by wildart** [JuliaLang/PkgDev.jl#8]
Provide interactive package generation as `generate` list of parameters is growing larger. If calling generate without any parameter then
- (Optional) Configure developer environment (minimal `git` configuration through `PkgDev.config`)
- Ask for the package name
  - Check if the name exists in METADATA and inform user
- Select license for the package (provide preview the license or its description or both)
  - Use bundled licenses
  - Use choosealicense.com licenses from https://github.com/github/choosealicense.com/tree/gh-pages/_licenses. These license files provide along with the license text, a description of the license as it is displayed on [choosealicense.com/licenses](http://choosealicense.com/licenses/).
- Ask if various developer services  (CI & coverage) are going to be used in the package development.
- Ask a location where to put the generated package.

All questions should provide a default answer except the package name.

**Comment by tkelman** [comment]
Package name probably shouldn't have a default.
