### ISSUE TITLE
GitError "Object is no commit object" on Pkg.publish()

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/PkgDev.jl#81]
``` julia
julia> using PkgDev

julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing Fontconfig permanent tags: v0.0.3
ERROR: GitError(Code:ERROR, Class:Invalid, Object is no commit object)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /Users/tamasnagy/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in publish(::String, ::String) at /Users/tamasnagy/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /Users/tamasnagy/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

Details:

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia> Pkg.status()
9 required packages:
 - Atom                          0.5.4
 - Cairo                         0.2.35
 - Colors                        0.6.8
 - Distributions                 0.11.0
 - Documenter                    0.4.4
 - Fontconfig                    0.0.3              master
 - PkgDev                        0.1.2
 - RDatasets                     0.2.0
 - Showoff                       0.0.7
82 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.3.1
 - AxisAlgorithms                0.1.5
 - BinDeps                       0.4.5
 - Blink                         0.4.2
 - COFF                          0.0.2
 - CRC                           1.2.0
 - Calculus                      0.1.15
 - CodeTools                     0.4.2
 - Codecs                        0.2.0
 - ColorBrewer                   0.3.0
 - ColorTypes                    0.2.8
 - Combinatorics                 0.3.2
 - Compat                        0.9.2
 - Compose                       0.4.4+             master
 - Contour                       0.2.0
 - DWARF                         0.1.0
 - DataArrays                    0.3.8
 - DataFrames                    0.8.4
 - DataStructures                0.4.6
 - Dates                         0.4.4
 - Distances                     0.3.2
 - DocStringExtensions           0.2.1
 - ELF                           0.1.0
 - FileIO                        0.2.0
 - FixedPointNumbers             0.1.8
 - FixedSizeArrays               0.2.4
 - ForwardDiff                   0.2.5
 - GZip                          0.2.20
 - Gadfly                        0.5.0
 - Gallium                       0.0.4
 - Graphics                      0.1.3
 - Hexagons                      0.0.4
 - Hiccup                        0.0.3
 - Homebrew                      0.4.0
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - HypothesisTests               0.4.0
 - Interpolations                0.3.6
 - Iterators                     0.1.10
 - JSON                          0.8.0
 - JuliaParser                   0.7.4
 - Juno                          0.2.3
 - KernelDensity                 0.3.0
 - LNR                           0.0.2
 - Lazy                          0.11.4
 - Loess                         0.0.7
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.3
 - Mustache                      0.1.2
 - Mux                           0.2.2
 - NaNMath                       0.2.1
 - ObjFileBase                   0.0.4
 - Optim                         0.6.1
 - PDMats                        0.5.0
 - Polynomials                   0.1.0
 - PositiveFactorizations        0.0.2
 - Primes                        0.1.1
 - RData                         0.0.4
 - Ratios                        0.0.4
 - Reactive                      0.3.5
 - Reexport                      0.0.3
 - Rmath                         0.1.3
 - Roots                         0.2.1
 - SHA                           0.2.1
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.11.0
 - StatsFuns                     0.3.1
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.0
 - YAML                          0.1.10
```

**Comment by tlnagy** [comment]
Actually, it looks like this error is caused by my setup. I generally rename my fork of a project as "origin" and the original as "upstream". Changing this to "downstream" and "origin", respectively seemed to fix this problem.

**Comment by tlnagy** [comment]
Actually it seems to be more complicated then that as I ran into this again and my above fix didn't seem to work.

**Comment by Datseris** [comment]
I just got the same error. Anyone knows any fix?

**Comment by tlnagy** [comment]
I don't remember how I got this working, but it was probably deleting and redownloading METADATA.jl (backing up the REQUIRES file first).

**Comment by tkelman** [comment]
Will need steps to reproduce if we're going to have any chance of determining what causes this.

**Comment by Datseris** [comment]
Hi @tkelman , I chose to simply use Attobot, and it worked for me so I am leaving this behind me...

**Comment by Datseris** [comment]
However, I will still try to help as much as I can:
The steps are the "standard" ones, as described in the docs. I did everything on github firstly. When my code was ready I first set the `git` username and email and name. Then I `Pkg.clone()`. After than I used the exact same steps for the publishing: first I didt `PkgDev.register()`, then I did `PkgDev.tag()`. I then did a second tagging because there was one github release that `tag()` did not do. Then I did `PkgDev.publish()` and got this error.

I know I may not be helping much but really, this is all I did as far as the Julia console goes...

**Comment by tkelman** [comment]
It's likely because you didn't create the package with `PkgDev.generate`, so were missing something it would have otherwise set.

**Comment by Datseris** [comment]
Actually this was the first step I did: I did `PkgDev.generate()` and then copied all the files from my local folder to github, and then worked from github

**Comment by tkelman** [comment]
Hm okay. Well anyone who this happens to again, if you could write down an exact set of steps, say starting from a clean separate JULIA_PKGDIR to get this to happen, it would be appreciated.

**Comment by billmclean** [comment]
I seem to have the same problem.

> julia> PkgDev.tag("GaussQuadrature", v"0.3.2")
INFO: Tagging GaussQuadrature v0.3.2
INFO: Committing METADATA for GaussQuadrature
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Creating a personal access token for Julia Package Manager on GitHub.
        You will be asked to provide credentials to your GitHub account.
Enter host password for user 'billmclean':
INFO: Pushing GaussQuadrature permanent tags: v0.3.2
ERROR: GitError(Code:ERROR, Class:Invalid, Object is no commit object)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #push#56(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#97(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:185
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /home/z8900007/.julia/v0.5/PkgDev/src/entry.jl:114
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:701
 in publish(::String, ::String) at /home/z8900007/.julia/v0.5/PkgDev/src/entry.jl:97
 in publish() at /home/z8900007/.julia/v0.5/PkgDev/src/PkgDev.jl:75

Previously, I had manually created the "v0.3.2" tag using git directly, but then deleted it so I could use PkgDev.tag and hence update my local METADATA.  I am using Julia 0.5.2 and the only installed packages are GaussQuadrature and PkgDev.

**Comment by billmclean** [comment]
I seem to be stymied.  My v0.3.2 tag exists, so doing `PkgDev.tag("GaussQuadrature", v"0.3.2")` results in
`ERROR: GitError(Code:EEXISTS, Class:Tag, Tag already exists)`
but my  METADATA still lists only up to v0.3.1 so doing `PkgDev.publish()` results in
`ERROR: There are no METADATA changes to publish`
How can I update the package to v0.3.2?

**Comment by ararslan** [comment]
@billmclean [Discourse](https://discourse.julialang.org) would likely be the best place to ask that question, but I imagine that's happening because the v0.3.2 tag exists in ~/.julia/v0.x/GaussQuadrature, it just isn't listed in ~/.julia/v0.x/METADATA/GaussQuadrature/versions. I'd delete it from the local clone of the package (as well as the remote, if it exists there) then try again.
