### ISSUE TITLE
config() won't recognize symlinked .gitconfig on mac.

### ISSUE THREAD

**Issue by abcsds** [JuliaLang/PkgDev.jl#82]
Good day, 
I ran PkgDev.config() on julia 0.5 Mac OS X:

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)
```

Right after asking for my github user, this error is thrown:

```
ERROR: GitError(Code:ERROR, Class:OS, failed to stat '/Users/abcsds/.gitconfig/Users/abcsds/.dotfiles/git/gitconfig.symlink': Not a directory)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in set!(::Base.LibGit2.GitConfig, ::String, ::String) at ./libgit2/config.jl:111
 in set!(::Base.LibGit2.GitConfig, ::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in config(::Bool) at /Users/abcsds/.julia/v0.5/PkgDev/src/PkgDev.jl:126
 in config() at /Users/abcsds/.julia/v0.5/PkgDev/src/PkgDev.jl:102
```

The actual gitconfig is `/Users/abcsds/.dotfiles/git/gitconfig.symlink'`, but it seems to be concatenating both the symlinked, and the original names.
`libgit2` is a dylib, so I'm gessing it has to do with how the `set()` function handles the .gitconfig name. Is that right?

_NOTE_: my gitconfig does not have my github user.

**Comment by tkelman** [comment]
Hard to tell whether this is a bug in the Julia bindings or in libgit2 itself. I'd usually suspect the former unless it gets traced down to the specific ccall and it looks like the inputs we give it match what the libgit2 documentation says we should be doing, in which case then we could write a C reproducer and report upstream. If it's a bindings problem, then maybe Gallium or manually tracing the inputs through this call chain could tell us where it's going wrong.
