### ISSUE TITLE
Default version chosen by PkgDev.tag is sometimes unacceptable to METADATA.jl

### ISSUE THREAD

**Issue by simonster** [JuliaLang/PkgDev.jl#88]
If the required Julia version has changed since the last minor release, `PkgDev.tag("PkgName")` should tag a new minor version rather than a patch.

**Comment by tkelman** [comment]
duplicate of https://github.com/JuliaLang/PkgDev.jl/issues/72

**Comment by simonster** [comment]
No, it's not. #72 is about PkgDev telling you when you screwed up. This is about making PkgDev not screw up.

**Comment by tkelman** [comment]
We should probably just deprecate single-argument tag, and always require you to specify whether you want patch, minor, or major. If you ask for patch when metadata would reject it, I could see making that give you a warning, or an "are you sure" confirmation prompt when in interactive mode.
