### ISSUE TITLE
Pkg.generate fails if `origin` remote already exists

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/PkgDev.jl#9]
Original issue:
https://github.com/JuliaLang/julia/issues/13527

**Comment by anthonyclays** [comment]
This appears to be fixed in PkgDev, however it has not been backported yet to 0.4.

**Comment by tkelman** [comment]
Thanks for the report. Can you help identify what the fix may have been?

**Comment by tkelman** [comment]
Bump. Anyone know what fixed this, or if this is still an issue? If it was fixed we should find out what change was responsible so 0.4 can also benefit.
