### ISSUE TITLE
PkgDev.generate should make an empty test/REQUIRE

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/PkgDev.jl#90]
A [question](https://discourse.julialang.org/t/dependency-only-for-testing/863) I asked on Discourse revealed the existence of `test/REQUIRE`, and a [PR by ChrisRackauckas](https://github.com/JuliaLang/julia/pull/19593) added documentation about it.

However, everything would be even more transparent if `PkgDev.generate` initialized a `test/README` which is empty, or has
```julia
# packages required for tests
```

**Comment by tkelman** [comment]
Bit of a downside to this is that if this file exists, then `Pkg.test` has to do extra work and will be slower - https://github.com/JuliaLang/julia/blob/57d7622378fe8214f7a5f2345645ff579029eb72/base/pkg/entry.jl#L726

We could rearrange that code a little and instead use whether or not `tests_require` is empty there, but that wouldn't help users until it made it into a backport release.

Another option would be adding a few comment lines of documentation explaining the `REQUIRE` file and the option of making a `test/REQUIRE`, or adding more information to the comments in the autogenerated `test/runtests.jl` file.

**Comment by tpapp** [comment]
I think in the long run it would be great if an empty `test/REQUIRE` did not add to execution time, then `PkgDev.generate` could create it. So perhaps code in `Pkg.test` needs to be fixed first.

**Comment by Nosferican** [comment]
The new Pkg system uses `extras` and `targets` so this is academic now. It should be closed.
