### ISSUE TITLE
Naming of PkgDev.tag is ambiguous

### ISSUE THREAD

**Issue by waldyrious** [JuliaLang/PkgDev.jl#91]
I might be mistaken, but from [this exchange](https://github.com/JuliaLang/METADATA.jl/pull/7488#discussion_r95064998), I'm under the impression that `PkgDev.tag()` doesn't actually create a *git* tag (the [documentation](https://github.com/JuliaLang/PkgDev.jl#tagpkg-ver-commit) doesn't seem to make it explicit one way or the other); if that is indeed the case, then it could be useful to rename `tag()` to something like `release()`.

**Comment by tkelman** [comment]
It does. That tag just has to be pushed to a different repo than the metadata contents, so if PkgDev.publish isn't working correctly it can be easy to forget to manually push the git tag.

**Comment by waldyrious** [comment]
Thanks for clarifying. In that case, it might be worth making the exact sequence of steps performed by PkgDev.tag() explicit in the documentation.
