### ISSUE TITLE
UpdateTag Feature

### ISSUE THREAD

**Issue by ccoffrin** [JuliaLang/PkgDev.jl#98]
In my experince, the workflow for updating a package is roughly,
1.  PkgDev.tag
2. PkgDev.publish
3. Make PR
4. Get feedback on proposed version
5. Update package code
6. Update version tag, by hand
7. Update metadata PR branch, by hand
8. PR accepted into METADATA

I recommend adding an UpdateTag capability to this package, that automates steps 6 and 7.

**Comment by KristofferC** [comment]
Consider using https://github.com/attobot/attobot
