### ISSUE TITLE
Scaling Julia package management for a wider audience

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/PkgDev.jl#99]
I recently stumbled over [this comment](https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935) by a member of GitHub's infrastructure team, which basically describes how the CocoaPods/Specs repository (which is basically for Swift and Objective C what METADATA.jl is for Julia) draws so much traffic that GitHub has no choice but to rate-limit it quite heavily (on its own, it consumes the capacity of several physical servers on GitHub's end...). I could not help but associate to how Julia does package management, and what we could do to protect ourselves against these kinds of problems in the future. (Of course, we're not Swift, so we shouldn't expect to see quite the same kinds of load... but still GitHub's infrastructure isn't free without limits.)

I can think of the following things we could do to lessen our dependency on GitHub and their infrastructure. Since I've been out of the Julia loop for quite a while, some or all of these might already have been discussed and rejected; in that case, I apologize for taking up your time...

* Consider making the default place to look for packages somewhere we host ourselves. Of course, there are costs associated with this, but I suspect that they are not very large today, so maybe e.g. the NumFocus foundation could carry them for now. When our capacity needs increase, we can scale up and out both the infrastructure and the search for sponsors.

* In order to facilitate the above, make it possible to register packages from other sources than GitHub. This has been mentioned quite a lot of times, but I don't know of any serious attempt to make it happen.

* Make it easier to have a bunch of metadata-like repositories to aggregate packages from, e.g. both METADATA.jl on GitHub and other sources elsewhere. This would de-centralize the entire package infrastructure, so there's probably a need for some discussion on how to prioritize when there are naming conflicts, etc.

* Consider using shallow clones in all fetch operations. Careful, though! As the comment linked to above outlines, doing this incorrectly could actually make the problems worse...

* If all else fails, consider redesigning the entire package redistribution system. NPM (for Node.js/JavaScript), NuGet (for .NET), and others have found quite successful models for how package distribution can be done, so we shouldn't have to re-invent the wheel.

Note: I'm not saying this is something we have to do now, or maybe ever. But given the problems others apparently have because they've chosen to build a package redistribution system entirely on GitHub, I think it merits some discussion.

**Comment by tkelman** [comment]
> make it possible to register packages from other sources than GitHub.

Already possible. We have a handful of registered packages that are on gitlab or bitbucket or private servers. Due to network effects it's less convenient to do so though.

> Consider using shallow clones in all fetch operations.

No, git handles shallow clones poorly, this makes things worse not better.

> everything else

Read https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md and the associated issues.

**Comment by tlycken** [comment]
@tkelman That Julep does indeed address all my concerns. Given a Pkg3 implementation that fulfills all (or most of) what's outlined there, I suspect we'll never end up where CocoaPods are/were.

Sorry for wasting some of your time... :( but thanks a lot for taking it to guide me to the discussion! :)
